### ISSUE TITLE
Fix the scroll container on Iphone5 of Transfer page

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#11]
![fix](https://user-images.githubusercontent.com/90451575/133275656-31bbcc9e-fb2e-4bc5-8e37-0a7ce0117452.jpg)

**Comment by felixangelini** [comment]
fixed in [commit](https://github.com/kadena-community/torus-wallet/commit/b3f3b922cc41d120be677cc2ff1ed59cf11a4a86)
