### ISSUE TITLE
Add "Any chain" on dropdown sender

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#12]
add on dropdown of sender chain a voice "Any chain". In this way it is possible to carry out a cross chain transfer by choosing only the receiver's chain.

Another option to add is chose the sender chain and automatically change the receiver chain with same chain. 
In this way it's possible to carry out a same chain transfer by choosing only the sender's chain

**Comment by felixangelini** [comment]
resolved in commit [src
added connecting loader, added logic transfer on dropdown chain](https://github.com/kadena-community/torus-wallet/commit/0d150d64e90e70cb5d84cce35775fd595fa5ddd7)
