### ISSUE TITLE
Problem with Crosschain transfer

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#16]
Scenario:

insert pubkey receiver
chose chain receiver
insert amount

return modal width fetch account error

in console have error like this: 

`transfer:1 Access to fetch at 'https://api.testnet.chainweb.com/chainweb/0.0/testnet04/chain/19/pact/api/v1/local' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by felixangelini** [comment]
Resolved in commit: [Fix bug transfer crosschain](https://github.com/kadena-community/torus-wallet/commit/3726c6c05b9f96cbc2c801dc3fab0e3dc61a3bd3)
