### ISSUE TITLE
filter the request key by public key

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#18]
If I had multiple account, the locale storage is the same for all account.
For this reason in History I see the transfer of all account and not only of my logged account

In my opinion shoulds filter the tx by pubkey logged in that moment

**Comment by felixangelini** [comment]
added filters in commit [added filters and controls on history section by public key](https://github.com/kadena-community/torus-wallet/commit/2c0ff77cd209318dec120cb032cc6864397d7bbc)
