### ISSUE TITLE
Fix Mobile layout on Transfer page

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#6]

**Comment by felixangelini** [comment]
fix in [commit](https://github.com/kadena-community/torus-wallet/commit/f3fd0be41f6f7fbac879a85c0274173cdf77b942)

![Immagine 2021-09-13 170701](https://user-images.githubusercontent.com/61802243/133109029-502f5dfa-ca66-4053-9edd-7d0f28fad5e5.jpg)
