### ISSUE TITLE
Add the possibility to select the sender Chain and the Receiver Chain

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#7]

**Comment by felixangelini** [comment]
In commit [Added Chain Switch, fix mobile layout, add validation, fix error popup
](https://github.com/kadena-community/torus-wallet/commit/f3fd0be41f6f7fbac879a85c0274173cdf77b942),

I've added a dropdown for sender chain (line 312) and one for receiver (line 343)
