### ISSUE TITLE
Add other validation on Form Transfer

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#8]
add validation:
1) ' Receiver must be at least 3 characters'
2) the chain selection is require

**Comment by felixangelini** [comment]
added in validationSchema (line 116) in commit [Added Chain Switch, fix mobile layout, add validation, fix error popup
](https://github.com/kadena-community/torus-wallet/commit/f3fd0be41f6f7fbac879a85c0274173cdf77b942)
