### ISSUE TITLE
Fix error when close google popup

### ISSUE THREAD

**Issue by wowkuro** [kadena-community/torus-wallet#9]
<img width="1144" alt="Screenshot 2021-09-10 at 5 23 46 PM" src="https://user-images.githubusercontent.com/90451575/133107674-73d80e12-213c-400a-98a3-18e0ae493ee4.png">

**Comment by felixangelini** [comment]
In commit [Added Chain Switch, fix mobile layout, add validation, fix error popup
](https://github.com/kadena-community/torus-wallet/commit/f3fd0be41f6f7fbac879a85c0274173cdf77b942),

I've added a catch control for fix the problem
